forget-players-on-quit = false

[scoreboard]
lines = [
    "%lines%",
    "",
    "<gray>turfwars.nickac.dev",
]

[database]
url = "jdbc:postgresql://localhost:5432/floofers"
username = "floofers"
password = "floofers"