[static-placeholders]
turfwars = "<gradient:#D80000:#EC0064:#CC23BA:#6068F9:#008BFF:#009DEA><bold>TurfWars</bold></gradient>"
prefix = "<gradient:#D80000:#EC0064:#CC23BA:#6068F9:#008BFF:#009DEA><bold>TurfWars</bold> > </gradient>"

[messages]
chat-message = "<player><reset>: <message>"