[game]
minimum-players = 2
maximum-players = 2
# The time in seconds that the lobby phase lasts (15 seconds)
lobby-countdown = 7

# The time in seconds that the build phase lasts (40 seconds)
build-time = 15

# The time in seconds that the battle phase lasts (60 seconds)
combat-time = 15

# The time in seconds that the game lasts (15 minutes)
end-time = 900

[game.turfs]
[game.turfs.red]
direction = "EAST"
[game.turfs.red.pos1]
x = 30
y = 74
z = -5
[game.turfs.red.pos2]
x = 34
y = 74
z = 5

[game.turfs.blue]
direction = "WEST"
[game.turfs.blue.pos1]
x = 39
y = 74
z = 5
[game.turfs.blue.pos2]
x = 35
y = 74
z = -5


[game.player-spawns]
[game.player-spawns.spectator]
x = 35.0
y = 84
z = 0

[[game.player-spawns.red]]
x = 26.5
y = 75
z = 0.5
yaw = -90
pitch = 0

[[game.player-spawns.blue]]
x = 43.5
y = 75
z = 0.5
yaw = 90
pitch = 0

[lobby]
x = 0.5
y = 75
z = 0.5
yaw = 0.0
pitch = 0.0