[game]
minimum-players = 2
maximum-players = 2
lobby-countdown = 15

[game.player-spawns]
[game.player-spawns.spectator]
x = 35.0
y = 84
z = 0

[[game.player-spawns.red]]
x = 20.5
y = 75
z = 0.5
yaw = -90
pitch = 0

[[game.player-spawns.blue]]
x = 49.5
y = 75
z = 0.5
yaw = 90
pitch = 0

[lobby]
x = 0.5
y = 75
z = 0.5
yaw = 0.0
pitch = 0.0