[minigame]
join = "<dark_gray>[<color:#20ff08>+</color>] <gray><player> is ready to fight!"
quit = "<dark_gray>[<color:#ff2008>-</color>] <gray><player> has places to be.."

start-countdown = "<dark_gray>[<color:#00b0f0>i</color>] <gray>The game starts in <yellow><time></yellow>."
not-enough-players = "<dark_gray>[<color:#ff2008>i</color>] <gray>Not enough players to start the game."

scoreboard-title = "<turfwars>"

scoreboard-players = "<white><current><gray>/</gray><max>"

team-switch-notification = "<prefix><green>You are now on the <team>."

unable-to-place-in-team = "<prefix><red>We were unable to place you in any playable team, thus you are now in the <team>."

block-break-not-allowed = "<prefix><red>You can only break blocks placed by other players."

debug = "<dark_gray>[<red>!</red>] <gray><message>"