[messages]
player-joined="<turfwars><yellow><player> joined the lobby."
player-left="<turfwars><yellow><player> left the lobby."

fell-in-lava="<red>Ouch! Careful not to fall in the lava!"

parkour-started="<turfwars><green>Parkour started."
parkour-cancelled="<turfwars><red>Parkour cancelled."
parkour-finished="<turfwars><green>Parkour finished!"
